### ISSUE TITLE
Missing result when searching through gazetter

### ISSUE THREAD

**Issue by bfiorito** [jjrom/resto#128]
Gazetteer search execute a 'like' request on toponym but an 'equal' request on over types (continent, country, state).
The consequence is that results are not  aggregate in the same request.
Eg : 
      `/resto2/api/gazetteer/search.json?q=haiti` 
returns
      `3 toponyms and 1 country`
whereas
 `/resto2/api/gazetteer/search.json?q=hait%`
returns 
     `30 toponyms but no country`

**Comment by jjrom** [comment]
This feature is addressed in GazetteerPro module and won't be fixed in Gazetteer module
