### ISSUE TITLE
Support EOP hierarchy in models

### ISSUE THREAD

**Issue by torse** [jjrom/resto#202]
Currently a sensor specific model needs to extends the default model to inherit several attributes from "General EO Products" like productIdentifier, platform, etc. It would be nice, if a sensor could also inherit from "Thematic EO Products" like OPT, SAR, ATM, ALT, LMB, SSP, etc. as defined in OGC 10-157r3.

**Comment by jjrom** [comment]
Major changed in resto v5 (https://github.com/jjrom/resto/commit/1dc86e5e71290e0ac406d838996c8f707aaa0f24)
This is no more applicable
