### ISSUE TITLE
Collections statitics count are always 0

### ISSUE THREAD

**Issue by avidot** [jjrom/resto#209]
When a collection is created, the counter of number of features per collection is not inserted into database.
And when we insert features, the counter is not updated because it is not present into database.

However, if we insert manually the counter into the "facets" table, the counter is correctly updated after features insertions.

**Comment by jjrom** [comment]
With the introduction of estimate_count (see https://github.com/jjrom/resto/commit/5f8e8bcef92ff8176025f23d5f51661837052dac), the facets table is not so useful. 
I do not plan to correct this issue in the near future. However, feel free to propose a correction on this issue through a pull request and i will review it for integration
