### ISSUE TITLE
Please use placeholders and remove all modification of data before it reaches the RDBMS

### ISSUE THREAD

**Issue by ukyg9e5r6k7gubiekd6** [jjrom/resto#223]
Is there a particular reason why this, and other code, isn't using placeholders?

https://github.com/jjrom/resto/blob/a7ef168f961ed55b9d747212c9b9ed60abb2638c/include/resto/Drivers/RestoDatabaseDriver_PostgreSQL.php#L598

Also, this is expensive - it round-trips to the RDBMS simply to do some string munging.

Also, there's no need to munge string data before it goes to the database. It seems the only use of this is to escape data so it can be substituted into the middle of SQL by callers. If those callers used placeholders (as they should), then this code wouldn't be required at all.

Also, why does this remove accents? There's nothing inherently wrong with searching for text including accents. Why prevent the user from searching for whatever takes their fancy today? Par exemple, pourqoi devrais-je être empêché de chercher le mot "Géographie"? Warum sollte ich nie nach "Flüsse" suchen?
I can't even begin to fathom how this approach would fare when faced with a language like Vietnamese.

Here's a good explanation of why you should use prepared statements and placeholders when accessing an RDBMS from code you're writing:

http://use-the-index-luke.com/sql/where-clause/bind-parameters

Here's the documentation on the function this code is using:

http://php.net/manual/en/function.pg-query.php

Notice how it says close to the top of the page:

> pg_query_params() should be preferred in most cases. 

This code and its callers are all such cases.

**Comment by ukyg9e5r6k7gubiekd6** [comment]
Yes, I feel much more comfortable running a PHP application if it never, ever calls pg_query or pg_escape_string.

This is a comparatively trivial change. Again, please re-open this and assign it to me, and I will send you a pull request over the Christmas period.

In general, if you think an issue I've raised is valid, but you don't intend to fix it yourself, rather than closing it, please feel free to assign it to me. I can't guarantee timeframes (like you I am not paid to work on this software), but I can guarantee effort and skill.

**Comment by ukyg9e5r6k7gubiekd6** [comment]
Regarding 2 - I think it would be better to use an algorithm like soundex or metaphone, or perhaps Unicode Normalization Form Canonical Decomposition, followed by optionally ignoring combining diacriticals. This needs careful discussion and testing, and is not something I intend to just leap into right now.

**Comment by jjrom** [comment]
1. I agree that placeholders provide a much more readable and maintainable code. If you are willing to propose a PR on it, it is more than welcome. Thanks for your proposal

2. You're absolutely right - my plan was to move to a clever algorithm but 1) I have no time to address this point and 2) my knowledge of natural languages processing is very minimalistic. It would be awesome if you can help on this point. And from a general point of view it is much more interesting that refactoring the pg_query :) We can discuss this by email/skype/whatever

**Comment by jjrom** [comment]
Corrected in resto v5 (https://github.com/jjrom/resto/commit/1dc86e5e71290e0ac406d838996c8f707aaa0f24)
