### ISSUE TITLE
Should use existing HTTP errors where they are applicable

### ISSUE THREAD

**Issue by ukyg9e5r6k7gubiekd6** [jjrom/resto#226]
How is this different from '409 Conflict'?

https://github.com/jjrom/resto/blob/a7ef168f961ed55b9d747212c9b9ed60abb2638c/include/resto/Utils/RestoLogUtil.php#L80

Note, HTTP permits you to use a human-readable string other than 'Conflict', if you choose (but broken clients may not be able to handle it).
Note, you can if you want to return a lengthy description of what went wrong in the HTTP body.

**Comment by jjrom** [comment]
You are right - this discrepancy is corrected in the proprietary fork of resto. I forgot to correct it in this version.
