### ISSUE TITLE
Please don't use the term "REST" when you don't really mean what it means

### ISSUE THREAD

**Issue by ukyg9e5r6k7gubiekd6** [jjrom/resto#228]
How about just calling this an "HTTP API" instead? That's accurate and honest.

https://github.com/jjrom/resto/blob/a7ef168f961ed55b9d747212c9b9ed60abb2638c/include/resto/RestoRoute.php#L19

The inventor of the term "REST", Roy Fielding, gets unhappy when people use the term "REST" to describe things like this which aren't REST, in this case (and many others) because they don't implement HATEAOS. Please don't make Roy even more unhappy than he already is.

Here is [Roy's dissertation where he coins the term "REST"](https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm).

Here is [Roy bemoaning people (like the authors of this software) misusing his terminology](https://www.infoq.com/articles/roy-fielding-on-versioning), and wondering why they (wrongly) think that HATEAOS is an optional part of REST, or not a constraint, or something unimportant.
It's almost like they didn't actually read and understand his dissertation...

**Comment by jjrom** [comment]
For the most part I have been developing this software on my spare time. I would have loved to have written perfect HATEOS/RESTful/etc API straight out of the box but unfortunately I'm not as skilled as you seems to be considering the very sufficient way you express yourself. So i had to make choice of what to implement first which lead me to consider that HATEAOS was less important than other aspect of what is called a REST API.

However the objective of resto is still to provide a compliant REST API -  as you seems very concerned by Roy Fielding's happiness I strongly invite you to send me a Pull Request with a right implementation

**Comment by ukyg9e5r6k7gubiekd6** [comment]
Sure - can you please re-open this issue and assign it to me?
I'll work on it over Christmas and send you a pull request.

A word of warning - I think that it will be an invasive change. Of course I will try to keep changes small and correct/complete, but it will be difficult. I will probably not be able to do that in all cases (or I'll get it wrong).

I assume that you want to maintain backward compatibility with existing clients, right?
In which case an API version increment is probably necessary.

**Comment by jjrom** [comment]
Could you please contact me privately before reopening this issue ?
