### ISSUE TITLE
Errors result in HTTP success 

### ISSUE THREAD

**Issue by ukyg9e5r6k7gubiekd6** [jjrom/resto#229]
This seems confused/wrong:

https://github.com/jjrom/resto/blob/a7ef168f961ed55b9d747212c9b9ed60abb2638c/include/resto/Resto.php#L166

If the HTTP status is 200, that means "success" - there was no error.
If there was an error, then the HTTP status must not be success.
If there was an error, but RESTo pretends to the client that there was not an error by saying "200 Ok", then RESTo is lying to the HTTP client.
Lying is nasty and bad. Good software doesn't lie.

**Comment by jjrom** [comment]
This behavior is explained in #227.
And you should definitively pay attention to the way you express your comments
