### ISSUE TITLE
Redundant ErrorCode in JSON response and HTTP status

### ISSUE THREAD

**Issue by ukyg9e5r6k7gubiekd6** [jjrom/resto#230]
This is redundant:

https://github.com/jjrom/resto/blob/a7ef168f961ed55b9d747212c9b9ed60abb2638c/include/resto/Resto.php#L169

HTTP already defines a status, which communicates to the client the success/failure of the client's request.
HTTP also defines a body, wherein the server can include a lengthy human-readable description of what went well or badly, why, and what the client's user might do about that.

Given that, there is no need for an attribute 'ErrorCode' in returned JSON responses. It adds nothing to the information already present.
Worse, this redundancy in the protocol allows RESTo to respond in apparently contradictory and possibly meaningless ways.

What does it mean if RESTo returns an HTTP status of 404 ("Not found"), but the HTTP body contains data that looks like the data I requested, with an ErrorCode indicating success? Is the 404 wrong (should be 200), because this is a successful request? Or should I trust the 404 (what I asked for doesn't exist)? In that case, what's this data in the body? Is it some other data that I didn't ask for?
Or if this circumstance is impossible, why does RESTo's protocol permit it?

What would it mean if RESTo returned "200 Ok", but then an HTTP body containing a JSON response containing an ErrorCode and not containing any data? How is this a success? Where is my data?

How am I to write a correct client for RESTo? I suppose I should:
1. Check the HTTP status. If it indicates an error, assume there has been an error, and attempt to handle it (perhaps, display a diagnostic). Stop.
2. Otherwise, check the content type. If it's not what I expected (eg not JSON), assume there's been an error, handle it, then stop.
3. Otherwise, if we got a JSON response, look for an ErrorCode attribute. If it's present, and it indicates an error, then assume the HTTP status was a lie, and there really has been an error, so attempt to handle the error, then stop.
4. Otherwise, if there's no ErrorCode or it indicates success, then go looking for data. If we find it, assume it's the data we want; use those data, then stop.
5. Otherwise, if there's no data, then assume that both the HTTP status and the ErrorCode are lies, and that something went wrong. But we have no idea what went wrong, so we can't really handle it meaningfully.

This is unnecessarily complex and difficult. Frameworks like Angular don't support this strange algorithm out of the box, so custom development is required. Novice Javascript programmers will almost certainly get such development wrong.

Using HTTP in general, and specifically using its status mechanism, is one of the core principles of REST API design.

**Comment by jjrom** [comment]
> How am I to write a correct client for RESTo?
Perhaps by starting to email me a nice message.

> What does it mean if RESTo returns an HTTP status of 404 ("Not found"), but the HTTP body contains data that looks like the data I requested, with an ErrorCode indicating success?

What you describe just never happens for the reason that the "errorCode" returned is the same as the HTTP error code returned by resto. So if HTTP status is 404, "errorCode" will be 404. Etc.

Why did I do this ? For a very pragmatic reason - if you copy/paste an url that is HTTP 400 in your browser, it will not tell you that there is a 400 error (unless you trap it through development window, etc.). With this implementation you'll get the error written in the browser and you know what happened. Yes this is redundant with http code, yes this is bad practice but it helps

**Comment by ukyg9e5r6k7gubiekd6** [comment]
In order for the author of a client to see that this never happens, he needs to read the server source code. Many novice web developers won't do this. From looking at the responses alone (which is all that many novices would do), it would appear that it can happen. This is unnecessarily misleading.

It would be much better if he could just generate a client using the Swagger API description, and even better if a more generic REST client could be used.

I understand, from what you said, that your intent was to describe to humans what happened, without requiring them to use web developer tools built into their browsers. Have I understood your explanation?

If so, then I do not think a JSON object containing a repetition of the HTTP status is the best way to communicate with people who don't like using developer tools.
It would be better to respond with a text/html body, containing a human-readable description of the problem, ideally localised to the user agent's declared language preference.

This is another thing I could fix, if you're willing. Again, re-open and assign to me if you like.

**Comment by jjrom** [comment]
> It would be better to respond with a text/html body, containing a human-readable description of the problem, ideally localised to the user agent's declared language preference

This is a good proposal - I re-open the issue and assign it to you. Thanks for your help !

**Comment by jjrom** [comment]
Corrected in resto v5 (https://github.com/jjrom/resto/commit/1dc86e5e71290e0ac406d838996c8f707aaa0f24)
