### ISSUE TITLE
This doesn't stream, and maybe it should

### ISSUE THREAD

**Issue by ukyg9e5r6k7gubiekd6** [jjrom/resto#231]
This buffers the entire response in PHP memory, then writes it out to the client.
If the response is large, and if it's of a type that the client could in principle handle incrementally (for example, it's in the progressive JPEG or JPEG 2000 image formats), then it would be better to stream the data out to the client as it's received/generated, using the ['chunked' transfer encoding introduced with HTTP 1.1](https://en.wikipedia.org/wiki/Chunked_transfer_encoding).

It's my understanding that one of the use cases for RESTo is serving JPEG 2000 data that originated from Sentinel-2 satellites, so this is something that might add significant value.

**Comment by jjrom** [comment]
Only json/xml data response is buffered in PHP memory then writes out to the client.
For binary data like images, data is streamed using HTTP 1.1 chunk transfer encoding as you can see here https://github.com/jjrom/resto/blob/2ae376c459e929113728521fc37bcac0dff33415/include/resto/RestoFeature.php#L273

Moreover, resto offers three streaming mechanism, pure php, apache XSendfile or Nginx streaming (see here https://github.com/jjrom/resto/blob/2ae376c459e929113728521fc37bcac0dff33415/include/resto/RestoFeature.php#L237)
