### ISSUE TITLE
FeatureCollection response has "properties", contradicting RFC 7946

### ISSUE THREAD

**Issue by treuherz** [jjrom/resto#232]
The [GeoJSON RFC](https://tools.ietf.org/html/rfc7946#section-7.1) states that FeatureCollections and Geometries "MUST NOT" contain a "properties" member, but Resto's search responses definitely do: https://github.com/jjrom/resto/blob/2ae376c459e929113728521fc37bcac0dff33415/include/resto/RestoFeatureCollection.php#L241-L251

I understand  that you need to return some information on the overall collection of search results, but why not use a [foreign member](https://tools.ietf.org/html/rfc7946#section-6.1) rather than contradicting the standard?

**Comment by jjrom** [comment]
Hi ! 
resto was developed years before the GeoJSON RFC. The GeoJSON output is based on the 2008 GeoJSON specification historically available at geojson.org. I did not take time to check the compliance with the specification so thank you for pointing out this inconsistency ! I hope that it's the only one :)
I will certainly follow your proposal to use a different property name to return this information in a future update

**Comment by jjrom** [comment]
Corrected https://github.com/jjrom/resto/commit/1dc86e5e71290e0ac406d838996c8f707aaa0f24
