### ISSUE TITLE
wrong path for php PID file

### ISSUE THREAD

**Issue by davidmichea** [jjrom/resto#237]
in file ./build/resto/container_root/etc/fpm/php-fpm.conf
line 17: pid = /run/php/php7.2-fpm.pid

Should it not be  /var/run/... ???

**Comment by davidmichea** [comment]
I found an existing /var/lib/php folder. Using it to store the PID file solved the problem.

**Comment by jjrom** [comment]
Thanks for pointing this out.
Absolutely it should be /var/run/php/php7.2-fpm.pid - corrected !
However since nginx and php-fpm are connected through http and not socket, it should work even with this typo...how did you get an error ? Did you change the nginx configuration ?
