### ISSUE TITLE
postgresql shared_buffers size

### ISSUE THREAD

**Issue by davidmichea** [jjrom/resto#238]
Hi,

This may not be a real issue, but the default settings for postgresql server in build/resto-database/postgresql.conf :
shared_buffers=8GB
Impeach me to start the DB on a 8GB RAM VM.

Maybe this should be noticed in the README file that this default configuration doesn't fit for machine with less than 8GB RAM ...

Cheers,
David

**Comment by jjrom** [comment]
Hi David,

Thanks for your comment - i updated the README and dev configuration accordingly

Jérôme
