### ISSUE TITLE
STAC class definitions

### ISSUE THREAD

**Issue by mattfung** [jjrom/resto#239]
Hello, 

I've recently tried to run resto via the `resto-stac` branch, but ran into problems because the class `STAC` is not defined.
https://github.com/jjrom/resto/blob/resto-stac/app/resto/core/api/ServicesAPI.php#L229 

I'm not an expert at PHP, but I'm wondering if there's some configuration that I have to do?

```
resto_1    | [16-Dec-2019 22:58:32] WARNING: [pool www] child 281 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined index: STAC in /app/resto/core/api/ServicesAPI.php on line 228"
```
Best,

**Comment by jjrom** [comment]
Hi,

The resto-stac branch is currently in development and should not be used. The STAC class is not publicly available right now which is why you get this warning. 
The resto-stac branch will be merge to the master branch once STAC v1.0 is released (i.e. late January)

Regards
