### ISSUE TITLE
Catalog can be missing description field, making it invalid

### ISSUE THREAD

**Issue by philvarner** [jjrom/resto#254]
https://tamn.snapplanet.io/catalogs/concepts is not a valid STAC Catalog because it does not have a "description" field, but is linked as a child rel from the root landing page. 

This triggers https://github.com/stac-utils/pystac/issues/464

One change that may be useful is to make `description` a required field when constructing Catalog objects (and I think it's required for Collection and Item too)

**Comment by jjrom** [comment]
@philvarner Thanks for pointing this out ! The issue was present in an external resto plugin. It is corrected with a check of the description as a required field as you suggest.
