### ISSUE TITLE
datetime filter disallows some valid strings and allows some invalid strings

### ISSUE THREAD

**Issue by philvarner** [jjrom/resto#267]
The following were found running stac-api-validator. There is a description on parsing datetimes in this PR https://github.com/radiantearth/stac-api-spec/pull/162/files 

The error response says:
```
"validateFilterString - Value for \"datetime\" must follow the pattern ^[a-zA-Z0-9\\-\\/\\.\\:]+$"
```
though this is not a correct regex for RFC3339 datetimes.

These datetime string used as a parameter to /search resulted in a 400, when they should be accepted:

- Search with datetime=1985-04-12T23:20:50,52Z returned status code 400
- Search with datetime=1996-12-19T16:39:57+00:00 returned status code 400
- Search with datetime=1996-12-19T16:39:57+08:00 returned status code 400
- Search with datetime=../1985-04-12T23:20:50.52Z returned status code 400
- Search with datetime=1985-04-12T23:20:50.52Z/.. returned status code 400
- Search with datetime=1985-04-12T23:20:50.52+01:00/1986-04-12T23:20:50.52Z+01:00 returned status code 400
- Search with datetime=1985-04-12T23:20:50.52-01:00/1986-04-12T23:20:50.52Z-01:00 returned status code 400
- Search with datetime=1937-01-01T12:00:27.87+01:00 returned status code 400
- Search with datetime=1937-01-01T12:00:27.8710+01:00 returned status code 400
- Search with datetime=1937-01-01T12:00:27.8+01:00 returned status code 400
- Search with datetime=2020-07-23T00:00:00.000+03:00 returned status code 400
- Search with datetime=2020-07-23T00:00:00+03:00 returned status code 400
- Search with datetime=1985-04-12t23:20:50.000z returned status code 400
- Search with datetime=1985-04-12 returned status code 200 instead of 400

These datetimes should not be accepted (because they are missing timezones), but were allowed:

- Search with datetime=1985-12-12T23:20:50.52 returned status code 200 instead of 400
- Search with datetime=1986-04-12T23:20:50.52Z/1985-04-12T23:20:50.52Z returned status code 200 instead of 400

**Comment by jjrom** [comment]
Thanks fo raising this issue ! Corrected in #271 and #272 with the following exception that still returns HTTP 400 Bad request errors :

* 1985-04-12T23:20:50,52Z (I don't think that comma is a valid separator for second fraction as RFC3339)
* 1986-04-12T23:20:50.52Z-01:00 (Is it valid to have a timezone modificator after Z character ???)
* 1986-04-12T23:20:50.52Z+01:00 (Is it valid to have a timezone modificator after Z character ???)

**Comment by philvarner** [comment]
> * 1985-04-12T23:20:50,52Z (I don't think that comma is a valid separator for second fraction as RFC3339)

See:https://datatracker.ietf.org/doc/html/rfc3339
 
time-fraction     = ("," / ".") 1*DIGIT

> * 1986-04-12T23:20:50.52Z-01:00 (Is it valid to have a timezone modificator after Z character ???)
> * 1986-04-12T23:20:50.52Z+01:00 (Is it valid to have a timezone modificator after Z character ???)

Oh! this is a bug in my validation code. Thanks, will fix it.

**Comment by jjrom** [comment]
Thanks for the feedback - PR #273 now support both comma and point as a valid separator for second fraction
