### ISSUE TITLE
Search with intersects geometry of type GeometryCollection fails

### ISSUE THREAD

**Issue by philvarner** [jjrom/resto#274]
From the validator (unmerged code):

GET Search with intersects={'type': 'GeometryCollection', 'geometries': [{'type': 'Point', 'coordinates': [100.0, 0.0]}, {'type': 'LineString', 'coordinates': [[101.0, 0.0], [102.0, 1.0]]}]} returned status code 400

**Comment by jjrom** [comment]
@philvarner Thanks for this. I've just added support to Geometrycollection for intersects.

However just a comment on the request. The JSON specification requires to use double quotes for property names so the correct request would be with double quotes not single quotes :

intersects={"type": "GeometryCollection", "geometries": [{"type": "Point", "coordinates": [100.0, 0.0]}, {"type": "LineString", "coordinates": [[101.0, 0.0], [102.0, 1.0]]}]}

**Comment by philvarner** [comment]
Yes, you're correct about the quotes -- that was output from Python of a dict, and I need to change the validation failure output to serialize it as JSON instead.
