### ISSUE TITLE
Limit value is restricted to 1 to 500, but this is not advertised properly in the service description

### ISSUE THREAD

**Issue by philvarner** [jjrom/resto#277]
The default `limit` parameter values are 1 to 10000. Implementations may restrict this, but it must be properly advertised in the service description. The resto service description has text describing this limit, but the values are not defined in the spec itself.

The schema for `limit` is currently:

```
"schema": {
    "type": "integer"
}
```

but instead should be:

```
"schema": {
    "type": "integer",
    "minimum": 1,
    "maximum": 500,
    "default": 50
}
```

**Comment by jjrom** [comment]
@philvarner Thanks for the feedback - corrected in #277
