### ISSUE TITLE
datetime warnings from stac-api-validator

### ISSUE THREAD

**Issue by philvarner** [jjrom/resto#307]
These are just warnings, since APIs are allowed to accept inputs that aren't necessarily valid STAC values.

double-open-ended queries are not allowed in STAC API:

- GET Search with datetime=/ returned status code 200 instead of 400
- GET Search with datetime=../.. returned status code 200 instead of 400
- GET Search with datetime=/.. returned status code 200 instead of 400
- GET Search with datetime=../ returned status code 200 instead of 400

invalid intervals (too many `/`):

- GET Search with datetime=/1984-04-12T23:20:50.52Z/1985-04-12T23:20:50.52Z returned status code 200 instead of 400
- GET Search with datetime=1984-04-12T23:20:50.52Z/1985-04-12T23:20:50.52Z/ returned status code 200 instead of 400
- GET Search with datetime=/1984-04-12T23:20:50.52Z/1985-04-12T23:20:50.52Z/ returned status code 200 instead of 400

comma as the fractional seconds separator is allowed in ISO8601 but not RFC3339
- GET Search with datetime=1985-04-12T23:20:50,52Z returned status code 200 instead of 400

**Comment by jjrom** [comment]
Thanks @philvarner ! Issue corrected in #308
