### ISSUE TITLE
Basic-CQL2 query filter=id='85583117-28cc-5b04-9b64-362cfb57c2eb' AND collection='S2' returns 400

### ISSUE THREAD

**Issue by philvarner** [jjrom/resto#322]
**Describe the bug**

`https://tamn.snapplanet.io/collections/S2/items?filter=id=%2785583117-28cc-5b04-9b64-362cfb57c2eb%27%20AND%20collection=%27S2%27` returns 400 error w/ msg `cql2FiltersToSQL - Unknown property in filter - id` even though `id` is advertised in queryabbles

**Comment by jjrom** [comment]
@philvarner Thanks !
