### ISSUE TITLE
Filter Ext Queryables endpoint content-type and $id incorrect

### ISSUE THREAD

**Issue by philvarner** [jjrom/resto#323]
**Describe the bug**

Queryables schema has two problems:

- [Item Search - Filter Ext] Queryables 'https://tamn.snapplanet.io/queryables' returned Content-Type header 'application/json', must return 'application/schema+json' (the link in the landing page for this is advertised correctly)
- [Item Search - Filter Ext] Queryables 'https://tamn.snapplanet.io/queryables' '$id' value invalid, must be same as queryables url -- this is set to `https://stac-api.example.com/queryables` (the value in the stac api spec example) instead of, e.g., `https://tamn.snapplanet.io/queryables` or `https://tamn.snapplanet.io/collections/S2/queryables`
- Collection resources (e.g., /collections/S2) is missing the queryables link rel (http://www.opengis.net/def/rel/ogc/1.0/queryables)

**Comment by jjrom** [comment]
@philvarner Thanks !
