### ISSUE TITLE
GET Search with ids and non-intersecting bbox returned results, indicating the ids parameter is overriding the bbox parameter.

### ISSUE THREAD

**Issue by philvarner** [jjrom/resto#324]
**Describe the bug**

GET Search with ids and non-intersecting bbox returned results, indicating the ids parameter is overriding the bbox parameter. All parameters are applied equally since STAC API 1.0.0-beta.1

`https://tamn.snapplanet.io/search?ids=7a1eb3b9-10bb-57d7-bc83-697bc87490b0&bbox=0,0,1,1` should not return any results because the footprint of this ID does not intersect the bbox, but the item is returned anyway. Searching with just `bbox=0,0,1,1` returns no results, which indicates the pre-1.0.0-beta.1 behavior of an ids parameter overriding all other parameters is still being used.

**Comment by jjrom** [comment]
@philvarner Thanks !
