### ISSUE TITLE
Search with limit above max advertised returns 400 instead of 200

### ISSUE THREAD

**Issue by philvarner** [jjrom/resto#337]
This was recently changed in 1.0.0-rc.2 to explicitly say that a 400 had to be returned if the limit value was above the max advertised, but then we realized this was inconsistent in OAFeat and has been clarified in in an unreleased version of that spec such that an error should not be returned, and instead the limit should be treated as if it were the maximum.

**Comment by jjrom** [comment]
Hi @philvarner - thanks for pointing this out !  I hope this is the last change to the limit property behavior :D

**Comment by philvarner** [comment]
> Hi @philvarner - thanks for pointing this out ! I hope this is the last change to the limit property behavior :D

Me too, LOL.
