### ISSUE TITLE
Wrong error code on authentication failure

### ISSUE THREAD

**Issue by lhcorralo** [jjrom/resto#339]
**Describe the issue**
When trying to update an item (using the PUT method), if authentication is set to BasicAuth and the user is invalid, the returned error code is 404 Not Found.

**Expected behavior**
The returned error should be 401 Unauthorized (or maybe 403 Forbidden)

**Additional context**
Trying to execute the same command without any kind of authentication leads to 401 Forbidden. The same if the user is valid, but the password is not (401 Unauthorized). I did not try other commands (like POST on items and collections, or DELETE on items).

**Comment by jjrom** [comment]
Hi @lhcorralo - thanks for raising this issue. Corrected in the latest built image
