### ISSUE TITLE
/children does not return all child link relations from landing page

### ISSUE THREAD

**Issue by philvarner** [jjrom/resto#354]
**Describe the bug**

On https://tamn.snapplanet.io, the https://tamn.snapplanet.io/children endpoint does not return all of the `child` link relations defined in the Landing Page links. the link with href https://tamn.snapplanet.io/collections is missing.

From the STAC API Children Extensions spec: `The /children endpoint must return the all the Catalog and Collection objects referenced by these child link relations.`

**Comment by jjrom** [comment]
@philvarner Thanks for raisins this issue - corrected in resto latest image and deployed on tamn.snapplanet.io

**Comment by philvarner** [comment]
Great, that passes now.
