### ISSUE TITLE
Do Features endpoints support fields, sort, and filter extensions?

### ISSUE THREAD

**Issue by philvarner** [jjrom/resto#359]
On tamn.snapplanet.io/, the conformance classes for STAC API - Item Search are advertised as:

    "https://api.stacspec.org/v1.0.0-rc.1/item-search",
    "https://api.stacspec.org/v1.0.0-rc.1/item-search#fields",
    "https://api.stacspec.org/v1.0.0-rc.1/item-search#sort",
    "https://api.stacspec.org/v1.0.0-rc.1/item-search#filter",

However, only STAC API - Features is advertised:

    "https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features",

with no extensions advertised. Typically, implementations support the same extensions on both the Item Search and Features endpoints, though this is not required (which is the point of having separate conformance classes like this!).  

I just wanted to check that the extensions shouldn't also be advertised for Features?

**Comment by jjrom** [comment]
Hi @philvarner - features endpoint support the same extensions as the STAC item search (i.e. fields, sort and filter). However I did not find how to advertise it in the conformance endpoint.

Do you mean I should I add these classes in the /conformance endpoint ?
```
"https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#fields"
"https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#sort"
"https://api.stacspec.org/v1.0.0-rc.1/ogcapi-features#filter"
```

**Comment by philvarner** [comment]
Correct.

**Comment by jjrom** [comment]
@philvarner Thanks ! Updated.
