### ISSUE TITLE
Sample bash scripts

### ISSUE THREAD

**Issue by samuelfooks** [jjrom/resto#379]
Using the API was fairly intuitive via the documentation, but some sample scripts for basic functions would have been handy in place of only 'good' and 'bad' responses.  Definitely keep in mind that I am newer to using STAC, and am building familiarity with APIs as well, so maybe not everyone will find my 'issues' super relevant.  

But I think some sample bash scripts could be added in the API documentation for users to be able to easily recursively delete catalogs and collections.  While I dont think emptying them first should not be necessary if the user has the proper authorization, but if the best manner for the API to work is just permitting item deletion then empty collection deletion and so forth.  At the very least a sample script to: find the catalog, the collections and items within and recursively delete the items, collections and then finally the catalog could be provided.    

While not necessary for the API function, it may increase the accessibility of the APIs use.

**Comment by jjrom** [comment]
Added a more easy to read documentation that would ease the writing of bash script https://github.com/jjrom/resto/blob/master/docs/COLLECTIONS_AND_CATALOGS.md

I'm looking forward contribution from users to write these bash scripts :)
