### ISSUE TITLE
Delete Catalog Function

### ISSUE THREAD

**Issue by samuelfooks** [jjrom/resto#380]
Currently I have digested a STAC catalog onto a resto instance and in the process of learning to use the uploading scripts, and some changing of names and the STAC structure ended up creating persistant data(metadata) for my STAC catalog.  There were some items that became duplicated after changing the name of my catalog and even after browsing the STAC hosted on catalog.edito-infra.mercator-ocean.eu/catalogs/catalogs, and seeing that all the collections and the items from within have been deleted.  The catalogs have stayed present, and thus will prevent an organized upload of a renewed catalog, that has the same title as the catalogs that stay on the resto instance. 

Much in the same way as to delete a collection, with the right authorization, deleting a catalog should also be possible.  

![Screenshot from 2023-07-24 09-11-46](https://github.com/jjrom/resto/assets/54527099/791571d4-f096-4bbc-94c3-7dfa3d412991)
![Screenshot from 2023-07-24 09-11-26](https://github.com/jjrom/resto/assets/54527099/f2921e36-5996-466f-ac2d-ac654d0b6e0c)
![Screenshot from 2023-07-24 09-11-07](https://github.com/jjrom/resto/assets/54527099/c17aa53c-5a69-41a9-9cec-dcec4ee6a9f9)
![Screenshot from 2023-07-24 09-10-59](https://github.com/jjrom/resto/assets/54527099/9442fbc6-75df-45c4-9aec-30d1d5ccb724)

**Comment by jjrom** [comment]
Added in [resto v8.0.7](https://github.com/jjrom/resto/releases/tag/v8.0.7)
