### ISSUE TITLE
Change user rights

### ISSUE THREAD

**Issue by Eldrile** [jjrom/resto#386]
Hello Jérome,
By looking into the code I don't see how to update user rights for them to be able "Create" and/or "Update".

There is a mention in the installation.md file of the fact that users should have these rights inside the PostgreSQL database but is there a way to add them through resto.
Furthermore, we would like user to have creation and update as default rights, is there any way to do that in resto configuration?

Thanks !

**Comment by jjrom** [comment]
Hi @Eldrile,

There is no way to set user rights from the API. This should be done directly within the database.
Furthermore, you cannot set default rights from the configuration.

These functionalities, including the support of groups creation, are part of a non-public resto addon. Open the source code of this addon can be discussed

Cheers
